car_rental/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # Dashboard
    # Cars
    path('cars', views.cars, name='cars'),
    path('car-cards', views.car_cards, name='car_cards'),
    path('car-detail/<int:id>', views.car_detail, name='car_detail'),
    path('car-delete/<int:id>', views.car_delete, name='car_delete'),
    path('car-edit/<int:id>', views.car_edit, name='car_edit'),
    # Clients
    path('clients', views.clients, name='clients'),
    path('client-profile-delete', views.client_profile_delete, name='client_profile_delete'),
    path('client-edit/<int:id>', views.client_edit, name='client_edit'),
    path('client-delete/<int:id>', views.client_delete, name='client_delete'),
    # Reservations
    path('reservations', views.reservations, name='reservations'),
    path('reservation-edit/<int:id>', views.reservation_edit, name='reservation_edit'),
    path('reservation-delete/<int:id>', views.reservation_delete, name='reservation_delete'),
    # Stats
    path('dashboard', views.stats, name='stats'),
    # Workers
    path('workers', views.users_list, name='workers'),
    path('worker-view/<int:id>', views.worker_view, name='worker_view'),
    # History
    path('history', views.history, name='history'),



    path('', views.login_view, name='login'),
    path('', views.logout_view, name='logout'),
    
    
    
    path('search/', views.search, name='search'),



    
    
    
    
    
    

    
    
    
    
    

    

    
]

valhalla_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car_rental.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

car_rental/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta, datetime, date
from decimal import Decimal
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    type = models.CharField(max_length=50)
    type_picture = models.ImageField(upload_to='tyoe-pictures/', null=True, blank=True)

    def __str__(self):
        return self.type
        


class Car(models.Model):

    car_status = [
        ('available','Available'),
        ('broke','Broke'),
        ('unavailable','Unavailable'),
        ('rented','Rented'),

    ]

    type = models.ForeignKey(Category, on_delete=models.PROTECT, null=True, blank=True)
    model = models.CharField(max_length=50)
    model_year = models.IntegerField(null=True, blank=True)
    matricule = models.CharField(max_length=50, null=False, blank=False)
    car_picture = models.ImageField(upload_to='car-pictures/', null=True, blank=True)
    price_day = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
    availability = models.BooleanField(default=True)
    status = models.CharField(max_length=50, choices=car_status, default='available', null=True, blank=True)
    problems = models.CharField(max_length=500, null=True, blank=True)
    problems_picture = models.ImageField(upload_to='car-pictures/', null=True, blank=True)
    color = models.CharField(max_length=10, null=True, blank=True)
    car_power = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.model
    




    

class Client(models.Model):

    genders = [
        ('male','Male'),
        ('female','Female'),
    ]

    client_picture = models.ImageField(upload_to='client-profile/', null=True, blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    CIN = models.CharField(max_length=50)
    birth_date = models.DateField()
    driver_license_number = models.CharField(max_length=50)
    gender = models.CharField(max_length=50, choices=genders)
    phone_number = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=50)
    passport_number = models.CharField(max_length=50, null=True, blank=True)
    passport_delivery = models.DateField(null=True, blank=True)
    availability = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    


    def total_amount_spent(self):
        # Calculate total amount spent on reservations
        total = sum(reservation.calculate_total_cost() for reservation in self.reservation_set.all())
        return total










########################


class Worker(models.Model):

    genders = [
        ('male','Male'),
        ('female','Female'),
    ]


    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='worker-profile/', null=True, blank=True)

    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    CIN = models.CharField(max_length=50, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)
    driver_license_number = models.CharField(max_length=50, null=True, blank=True)
    phone_number = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=50, choices=genders, null=True, blank=True)
    email = models.EmailField(max_length=50, null=True, blank=True)
    availability = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    
    
    def __str__(self):
        return self.user.username


########################


class Reservation(models.Model):
    reservation_status = {
        ('active','Active'),
        ('ended','Ended'),
    }
    parking_locations = {
        ('parking_a','Parking A'),
        ('parking_b','Parking B'),
    }

    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    livraison_location = models.CharField(max_length=50)
    livraison_time = models.TimeField(auto_now=False, auto_now_add=False)
    money_guarantee = models.IntegerField(null=True, blank=True)
    fuel_gas = models.IntegerField(null=True, blank=True)
    parking = models.CharField(max_length=50, choices=parking_locations, null=True, blank=True)
    availability = models.BooleanField(default=True)

    status = models.CharField(max_length=10, choices=reservation_status, default='active', null=True, blank=True)
    car_status = models.CharField(max_length=50, choices=Car.car_status, null=True, blank=True, default='rented')
    worker = models.ForeignKey(Worker, on_delete=models.PROTECT, null=True, blank=True)
    recuperation_time = models.TimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    recuperation_location = models.CharField(max_length=50, null=True, blank=True)
    report = models.CharField(max_length=50, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)


    def total_days(self):
        if self.start_date and self.end_date:
            return (self.end_date - self.start_date).days
        return 0

    def total_amount(self):
        return self.total_days() * self.car.price_day if self.start_date and self.end_date else Decimal('0.00')


    def calculate_total_cost(self):
        # Calculate the number of days rented, ensuring start and end date count correctly
        duration = (self.end_date - self.start_date).days
        if duration == 0:  # Same day rental
            duration = 1
        total_cost = duration * self.car.price_day
        return total_cost
    

    def __str__(self):
        return self.car.model
    








    

















class Notification(models.Model):
    message = models.CharField(max_length=255)
    recipient = models.ForeignKey(User, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

















class UserActionLog(models.Model):
    ACTION_CHOICES = [
        ('add', 'Add'),
        ('update', 'Update'),
        ('delete', 'Delete'),
        ('create', 'Create'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    action = models.CharField(max_length=10, choices=ACTION_CHOICES)
    timestamp = models.DateTimeField(auto_now_add=True)
    description = models.TextField()

    def __str__(self):
        return f"{self.user.username} - {self.action} - {self.timestamp}"

templates/pages/car-delete.html
{% extends 'base.html' %}

{% block content %}



<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            

            <form method="POST">
                {% csrf_token %}
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <div class="card text-center">
                                <div class="card-body">
                                    <h5 class="card-title">Are you sure you want to delete this car?</h5>
                                    <p>If you delete it all reservations with this car will be delete</p>
                                    <a href="{% url "cars" %}" class="btn btn-light m-2">Back</a>
                                    <button type="submit" class="btn btn-danger m-2">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</div>





{% endblock %}

templates/pages/car-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    *{
    box-sizing: border-box;
    padding: 0;
    margin: 0;
    font-family: 'Open Sans', sans-serif;
    }
    body{
        line-height: 1.5;
    }
    
    img{
        width: 100%;
        display: block;
        height: 100%;
        
    }
    .img-display{
        overflow: hidden;
        
    }
    .img-showcase{
        display: flex;
        width: 100%;
        transition: all 0.5s ease;
        
    }
    .img-showcase img{
        min-width: 100%;
        
    }
    .img-select{
        display: flex;
        
    }
    .img-item{
        margin: 0.3rem;
        
    }
    .img-item:nth-child(1),
    .img-item:nth-child(2),
    .img-item:nth-child(3){
        margin-right: 0;
    }
    .img-item:hover{
        opacity: 0.8;
    }
    .product-content{
        padding: 2rem 1rem;
    }
    .product-title{
        font-size: 3rem;
        text-transform: capitalize;
        font-weight: 700;
        position: relative;
        color: #12263a;
        margin: 1rem 0;
    }
    .product-title::after{
        content: "";
        position: absolute;
        left: 0;
        bottom: 0;
        height: 4px;
        width: 80px;
        background: #12263a;
    }
    .product-link{
        text-decoration: none;
        text-transform: uppercase;
        font-weight: 400;
        font-size: 0.9rem;
        display: inline-block;
        margin-bottom: 0.5rem;
        background: #256eff;
        color: #fff;
        padding: 0 0.3rem;
        transition: all 0.5s ease;
    }
    .product-link:hover{
        opacity: 0.9;
    }
    .product-rating{
        color: #ffc107;
    }
    .product-rating span{
        font-weight: 600;
        color: #252525;
    }
    .product-price{
        margin: 1rem 0;
        font-size: 1rem;
        font-weight: 700;
    }
    .product-price span{
        font-weight: 400;
    }
    .last-price span{
        color: #f64749;
        text-decoration: line-through;
    }
    .new-price span{
        color: #256eff;
    }
    .product-detail h2{
        text-transform: capitalize;
        color: #12263a;
        padding-bottom: 0.6rem;
    }
    .product-detail p{
        font-size: 0.9rem;
        padding: 0.3rem;
        opacity: 0.8;
    }
    .product-detail ul{
        margin: 1rem 0;
        font-size: 0.9rem;
    }
    .product-detail ul li{
        margin: 0;
        list-style: none;
        background: url(shoes_images/checked.png) left center no-repeat;
        background-size: 18px;
        padding-left: 1.7rem;
        margin: 0.4rem 0;
        font-weight: 600;
        opacity: 0.9;
    }
    .product-detail ul li span{
        font-weight: 400;
    }
    
    

    @media screen and (min-width: 992px){
        .card{
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            grid-gap: 1.5rem;
        }
        .card-wrapper{
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .product-imgs{
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
        .product-content{
            padding-top: 0;
        }
    }
  </style>
  <div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
    <div class = "card">
      <!-- card left -->
      <div class = "product-imgs">
        <div class = "img-display">
          <div class = "img-showcase">
            {% if car.car_picture %}
            <img src = "{{car.car_picture.url}}">
            {% else %}
            <img src = "{% static "images/cars-cards.png" %}">
            {% endif %}
            <!--
            <img src = "https://francuskie.pl/wp-content/uploads/2022/10/dacia-duster-mat-edition-202290523-1666085786_1.jpg" alt = "shoe image">
            <img src = "https://francuskie.pl/wp-content/uploads/2022/06/Dacia-Duster-tuningn-Carpoint.jpg" alt = "shoe image">
            <img src = "https://dacia.press/wp-content/uploads/2023/06/Dacia-Duster-2023.jpeg" alt = "shoe image">
          -->
          </div>
        </div>
        <div class = "img-select">
          <!--

          <div class = "img-item">
            <a href = "#" data-id = "1">
              <img src = "" alt = "shoe image">
            </a>
          </div>
          <div class = "img-item">
            <a href = "#" data-id = "2">
              <img src = "https://francuskie.pl/wp-content/uploads/2022/10/dacia-duster-mat-edition-202290523-1666085786_1.jpg" alt = "shoe image">
            </a>
          </div>
          <div class = "img-item">
            <a href = "#" data-id = "3">
              <img src = "https://francuskie.pl/wp-content/uploads/2022/06/Dacia-Duster-tuningn-Carpoint.jpg" alt = "shoe image">
            </a>
          </div>
          <div class = "img-item">
            <a href = "#" data-id = "4">
              <img src = "https://dacia.press/wp-content/uploads/2023/06/Dacia-Duster-2023.jpeg" alt = "shoe image">
            </a>
          </div>
          -->
        </div>
      </div>
      <!-- card right -->
      <div class = "product-content">
        <h2 class = "product-title">{{car.type}}</h2>
        <a href = "#" class = "product-link">{{car.model}}</a>
        

        <div class = "product-price">
          <p class = "new-price">Price: <span> {{car.price_day}} DH </span></p>
        </div>

        <div class = "product-detail">
          <h2>Informations: </h2>
          <ul>
            <li>Model Year: <span>{{car.model_year}}</span></li>
            <li>Registration N°: <span>{{car.matricule}}</span></li>
            <li>Color: <span>{{car.color}}</span></li>
            {% if car.status == 'available' %}
            <li class="list-group-item">Status: <label class="badge badge-success">{{car.status}}</label></li>
            {% elif car.status == 'rented' %}
            <li class="list-group-item">Status: <label class="badge badge-info">{{car.status}}</label></li>
            {% elif car.status == 'broke' %}
            <li class="list-group-item">Status: <label class="badge badge-warning">{{car.status}}</label></li>
            {% elif car.status == 'unavailable' %}
            <li class="list-group-item">Status: <label class="badge badge-danger">{{car.status}}</label></li>
            {% else %}
            <li class="list-group-item">Status: <label class="badge badge-dark">{{car.status}}</label></li>
            {% endif %}
            <!-- Display Parking Information -->
    {% if car.reservation_set.exists %}
        {% for reservation in car.reservation_set.all %}
        {% if reservation.parking %}
        <li>Parking: {{ reservation.parking }}</li>
        {% endif %}
        {% endfor %}
    
        {% endif %}
            <li>Car Power: <span>{{car.car_power}}</span></li>
          </ul>
        </div>
        <h2>Problem Description: </h2>
            <p>{{car.problems}}</p>
        <h2>Problem Picture: </h2>
        {% if car.problems_picture %}
        <img style="width: auto; height: 100px; margin-bottom:30px;" src = "{{car.problems_picture.url}}" alt = "shoe image">
        {% else %}
        <p>None</p>
        {% endif %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{% url "car_cards" %}" class="btn btn-light me-md-2" type="button">Back</a>
        </div>

        
      </div>
    </div>
  </div>
  </div>
  </div>
  </div>






{% endblock %}

templates/pages/car-edit.html
{% extends 'base.html' %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-12 grid-margin">
            <div class="card">
            <div class="card-body">
                <h4 class="card-title">Horizontal Two column</h4>
                    <form class="form-sample" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p class="card-description"> Personal info </p>
                            {{form}}
                            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                <a href="{% url "cars" %}" class="btn btn-light me-md-2" type="button">Back</a>
                                <button class="btn btn-success" type="submit">Save</button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/pages/client-delete.html
{% extends 'base.html' %}

{% block content %}



<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <form method="POST">
                {% csrf_token %}
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <div class="card text-center">
                                <div class="card-body">
                                    <h5 class="card-title">Are you sure you want to delete this Client?</h5>
                                    <p>If you delete it all reservations with this client will be delete</p>
                                    <a href="{% url "clients" %}" class="btn btn-light m-2">Back</a>
                                    <button type="submit" class="btn btn-danger m-2">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

</div>





{% endblock %}

templates/pages/client-edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="main-panel">
    <div class="content-wrapper">
<div class="container rounded bg-white mb-5">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                {% if form.instance.client_picture %}
                        <img id="profile_picture" class="rounded-circle mt-5" width="150px" src="{{ form.instance.client_picture.url }}">
                    {% else %}
                        <img id="profile_picture" class="rounded-circle mt-5" width="150px" src="{% static 'images/faces/face28.png' %}">
                    {% endif %}
                    <span id="full_name" class="font-weight-bold">{{ form.instance.first_name }} {{ form.instance.last_name }}</span>
                    <span id="profile_email" class="text-black-50">{{ form.instance.email }}</span>
                </div>
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Client Profile</h4>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><label class="labels">First Name</label>{{form.first_name}}</div>
                    <div class="col-md-6"><label class="labels">Last Name</label>{{form.last_name}}</div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">CIN</label>{{form.CIN}}</div>
                    <div class="col-md-12"><label class="labels">Birth Date</label>{{form.birth_date}}</div>
                    <div class="col-md-12"><label class="labels">Driver License N°</label>{{form.driver_license_number}}</div>
                    <div class="col-md-12"><label class="labels">Gender</label>{{form.gender}}</div>
                    <div class="col-md-12"><label class="labels">Phone N°</label>{{form.phone_number}}</div>
                    <div class="col-md-12"><label class="labels">Email</label>{{form.email}}</div>
                    <div class="col-md-12"><label class="labels">Address</label>{{form.address}}</div>
                    <div class="col-md-12"><label class="labels">Passport N°</label>{{form.passport_number}}</div>
                    <div class="col-md-12"><label class="labels">Passport delivery</label>{{form.passport_delivery}}</div>
                </div>
                <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="submit">Save Profile</button></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center experience"><span>Edit Profile</span></div><br>
                <div class="col-md-12"><label class="labels">Client Profile</label>{{form.client_picture}}</div> <br>
            </div>
        </div>
    </div>
</form>
</div>
</div>
</div>
</div>
</div>
</div>




{% endblock %}

templates/pages/end-reservations.html
{% extends 'base.html' %}

{% block content %}





{% endblock %}

templates/pages/history.html
{% extends 'base.html' %}

{% block content %}





<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">History table</h4>
        </p>
        <div class="table-responsive pt-3">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th> User </th>
                <th> Action </th>
                <th> Timestamp </th>
                <th> Description </th>
              </tr>
            </thead>
            <tbody>
                {% for log in logs %}
              <tr>
                <td> {{ log.user.username }} </td>
                <td> {{ log.get_action_display }} </td>
                <td> {{ log.timestamp }} </td>
                <td> {{ log.description }} </td>
              </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
  </div>
  </div>











{% endblock %}

templates/pages/index.html
{% extends "base.html" %}

{% block content %}


<!-- partial -->
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-sm-12">
          <div class="home-tab">
            <div class="tab-content tab-content-basic">
              <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview">
                
                
                <div class="col-lg-12 grid-margin stretch-card">
                  <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Cars</h4>
                        <div class="table-responsive">
                          <table class="table table-striped">
                            <thead>
                              <tr>
                                <th> Type </th>
                                <th> Model </th>
                                <th> Registration N° </th>
                                <th> Status </th>
                              </tr>
                            </thead>
                            
                            <tbody>
                              {% for car in cars %}
                              <tr>
                                <td> {{car.type}} </td>
                                <td> {{car.model}} </td>
                                <td> {{car.matricule}} </td>
                                <td>
                                  {% if car.status == 'available' %}
                                  <label class="badge badge-success">{{car.status}}</label>
                                  {% elif car.status == 'rented' %}
                                  <label class="badge badge-info">{{car.status}}</label>
                                  {% elif car.status == 'broke' %}
                                  <label class="badge badge-warning">{{car.status}}</label>
                                  {% elif car.status == 'unavailable' %}
                                  <label class="badge badge-danger">{{car.status}}</label>
                                  {% else %}
                                  <label class="badge badge-dark">{{car.status}}</label>
                                  {% endif %}
                                </td>
                              </tr>
                              {% endfor %}
                            </tbody>
                            
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <!-- content-wrapper ends -->




{% endblock %}

templates/pages/login.html
{% load static %}
<!-- templates/registration/login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <!-- Add Bootstrap CSS or other styles here -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }
        
        body {
            background: #ecf0f3;
        }
        
        .wrapper {
            max-width: 350px;
            min-height: 500px;
            margin: 200px auto;
            padding: 40px 30px 30px 30px;
            background-color: #ecf0f3;
            border-radius: 15px;
            box-shadow: 13px 13px 20px #cbced1, -13px -13px 20px #fff;
        }
        
        .logo {
            width: 80px;
            margin: auto;
        }
        
        .logo img {
            width: 100%;
            height: 80px;
            object-fit: cover;
            border-radius: 50%;
            box-shadow: 0px 0px 3px #5f5f5f,
                0px 0px 0px 5px #ecf0f3,
                8px 8px 15px #a7aaa7,
                -8px -8px 15px #fff;
        }
        
        .wrapper .name {
            font-weight: 600;
            font-size: 1.4rem;
            letter-spacing: 1.3px;
            padding-left: 10px;
            color: #555;
        }
        
        .wrapper .form-field input {
            width: 100%;
            display: block;
            border: none;
            outline: none;
            background: none;
            font-size: 1.2rem;
            color: #666;
            padding: 10px 15px 10px 10px;
            /* border: 1px solid red; */
        }
        
        .wrapper .form-field {
            padding-left: 10px;
            margin-bottom: 20px;
            border-radius: 20px;
            box-shadow: inset 8px 8px 8px #cbced1, inset -8px -8px 8px #fff;
        }
        
        .wrapper .form-field .fas {
            color: #555;
        }
        
        .wrapper .btn {
            box-shadow: none;
            width: 100%;
            height: 40px;
            background-color: #03A9F4;
            color: #fff;
            border-radius: 25px;
            box-shadow: 3px 3px 3px #b1b1b1,
                -3px -3px 3px #fff;
            letter-spacing: 1.3px;
        }
        
        .wrapper .btn:hover {
            background-color: #039BE5;
        }
        
        .wrapper a {
            text-decoration: none;
            font-size: 0.8rem;
            color: #03A9F4;
        }
        
        .wrapper a:hover {
            color: #039BE5;
        }
        
        @media(max-width: 380px) {
            .wrapper {
                margin: 30px 20px;
                padding: 40px 15px 15px 15px;
            }
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="logo">
            <img src="{% static "images/logoo_mini.png" %}" alt="">
        </div>
        <div class="text-center mt-4 name">
            RPM
        </div>
        <form class="p-3 mt-3" method="POST">
            {% csrf_token %}
            <div class="form-field d-flex align-items-center">
                <span class="far fa-user"></span>
                {{ form.username }}
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                {{ form.password }}
            </div>
            <button type="submit" class="btn mt-3">Login</button>
        </form>
        {% if messages %}
        <div class="mt-3">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            </div>
        {% endif %}
        <div class="text-center fs-6">
            Click <a style="font-size: 16px;" href="mailto:samyakli685@gmail.com?subject=Password%20Reset%20Request">Forget password</a> to email the administrator for information reset.
        </div>
    </div>
</body>
</html>